version: '3'
services:
  # React
  react-app:
    image: rimibnm/img_react
    ports:
      - "3000:3000"

  # Spring Boot
  spring-app:
    image: rimibnm/img_backendvoiture
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    networks:
      - my-network

  # MySQL Service
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullstack
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network: